---
title: "README"
author: "Jesus Ortiz"
date: "2023-08-06"
output: html_document
---

# Getting and Cleaning Data Course Project

This repository contains the submission by Jesus Ortiz for the "Getting and Cleaning Data" course project. It demonstrates the process of analyzing the "Human Activity Recognition Using Smartphones" dataset.

## Dataset

The dataset used for this project is the "Human Activity Recognition Using Smartphones" dataset. It contains data collected from smartphones worn by subjects while performing various activities. The goal is to clean and transform the raw data to obtain a tidy dataset that is more suitable for analysis.

## Files

This repository contains the following files:

- `Codebook.md`: A code book that provides details about the variables, data, and the data cleaning process. It explains the transformations and steps taken to create the final tidy dataset.

- `run_analysis.R`: This R script performs the data preparation and follows the five steps required as described in the course project’s definition:

  1. Merges the training and the test sets to create one data set.
  2. Extracts only the measurements on the mean and standard deviation for each measurement.
  3. Uses descriptive activity names to name the activities in the data set.
  4. Appropriately labels the data set with descriptive variable names.
  5. Creates a second, independent tidy data set with the average of each variable for each activity and each subject.

- `final_data.txt`: This is the exported final tidy data file after going through all the sequences described above. It contains the average of each variable for each activity and each subject.

## Instructions

To reproduce the analysis and obtain the final tidy dataset, follow these steps:

1. Clone or download this repository to your local machine.
2. Open the R script `run_analysis.R` in RStudio or any other R environment.
3. Ensure that the necessary packages (e.g., `dplyr`) are installed by running `install.packages("dplyr")` if needed.
4. Set your working directory to the location where the script and the dataset files are located.
5. Run the script. It will perform the data preparation, transformation, and generate the final tidy dataset in a file named `final_data.txt`.

## Acknowledgments

The "Human Activity Recognition Using Smartphones" dataset was obtained from the UCI Machine Learning Repository.

## License

This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.
